#!/bin/bash

editor="gedit"
notesdir="/home/$USER/Documents/Notes"

if [ -z $1 ]; then
    filename="note-$(date +%d_%m_%y-%H:%M).txt"
    $editor $notesdir/$filename >& /dev/null &
    exit 0
fi

optstring="hlr"

while getopts ${optstring} arg; do
    case $arg in
        h)
            echo "Usage: $0 [-hlr]"
            echo "  No options: Opens new note in $editor"
            echo "  -h: Shows this help message"
            echo "  -l: Lists all notes in notes directory"
            echo "  -r: Opens most recent note in $editor"
            ;;
        l)
            ls -t $notesdir
            ;;
        r)
            $editor $notesdir/$(ls -t $notesdir | head -n 1) >& /dev/null &
            ;;
        ?)
            echo "Invalid arg"
            exit 1
            ;;
    esac
done
